title: "jdelossantos"
description: "Un poco de Python, MATLAB, FEA y Robótica"
baseurl: "/blog"  # ruta del blog
url: "https://jorgedelossantos.github.io"

theme: minima   # tema por defecto de Jekyll

